### PR TITLE
Don't override callback_url Attempt to correct #28

### PR DESCRIPTION
**Pull request by agrobbin**
I hope nobody minds me issuing this PR. It bit us pretty hard and would be great to get it merged into master!

Overridden method discarded the query_string

### CODE REVIEW

**Comment by stereobooster** [comment]
:+1:

**Comment by sferik** [comment]
According to #28 this breaks Google, Spotify and Beats, so I don’t think it can be merged yet.

**Comment by timherby** [comment]
This would very very useful for us as well.  Works fine with LinkedIn and Facebook.  We have a workaround in place for now.  Would love to see this merged (at least as a configurable option)

**Comment by timherby** [comment]
Cool, thanks for merging!

**Comment by sferik** [comment]
Thanks for the pull request. Released in [version 1.4.0](https://github.com/intridea/omniauth-oauth2/tree/v1.4.0).

**Comment by philrosenstein** [comment]
This change caused issues for me in writing a custom strategy for ADP.  Similar to LinkedIn, the redirect_url must match exactly what they have on file, so having extra parameters in the query string causes the token request to fail.  I had to use a workaround as suggested by @jtokoph in this issue https://github.com/WebTheoryLLC/omniauth-twitch/issues/3

So it would appear this patch made life easier for some integrations, but harder for others..

**Comment by codeanpeace** [comment]
Thoughts on better documenting this behavior? Found myself in similar boat as @philrosenstein recently when writing a custom strategy. There's a related open issue here #93 .

**Comment by ptoomey3** [comment]
cross-linking/pasting https://github.com/omniauth/omniauth-oauth2/pull/82#issuecomment-567728229 since this is a different set of folks. In short, by my read of the spec. Looking at the RFC:  https://tools.ietf.org/html/rfc6749#section-4.1.3

> redirect_uri
>         REQUIRED, if the "redirect_uri" parameter was included in the
>         authorization request as described in Section 4.1.1, and their
>         values MUST be identical.

The RFC says that the `redirect_uri` you pass to the server when exchange `code` for `access_token` must be _identical_ to the one in the original authorization request. The original "fix" in https://github.com/omniauth/omniauth-oauth2/pull/70 doesn't do that. By including the query params it will in fact vary by definition since the first step in the flow won't have a `code` in the query string and the final step will.

**Comment by pboling** [comment]
@sferik Can you take another look at this?  Upgrading past v1.3 is breaking `omniauth-greenhouse`, and from the above refs it appears to break many integrations because it doesn't follow the oauth 2.0 spec, as noted by @ptoomey3 above.

**Pull request merged**
